###############################################
# Example configuration (sanitized for commit) #
# Fill in real values before running.          #
###############################################

access_key: "YOUR_PICOVOICE_ACCESS_KEY"          # obtain from https://console.picovoice.ai/
wakeword_path: "YOUR_KEYWORD_FILE.ppn"           # e.g. Alfredo_pt_windows_v3_0_0.ppn
model_path: "porcupine_params_<lang>.pv"         # e.g. porcupine_params_pt.pv

recording:
  silence_threshold: 500          # amplitude below this int16 peak is considered silence
  silence_duration_seconds: 3     # stop after this many seconds of continuous silence
  max_record_seconds: 120         # hard cap on recording length
  output_dir: "recordings"        # folder to store wav files before (maybe) deletion

# Audio webhooks list (wav uploads)
audio_webhooks:
  - url: "https://primary.example.com/webhook/audio"    # primary
    timeout_seconds: 10
    file_field_name: "audio_file"
    debug: true
  - url: "https://fallback.example.com/webhook/audio"   # fallback
    timeout_seconds: 30
    file_field_name: "audio_file"
    debug: true

# Text webhooks list (manual 'q' key JSON text)
text_webhooks:
  - url: "https://primary.example.com/webhook/text"   # first text endpoint
    timeout_seconds: 10
    debug: true
  - url: "https://fallback.example.com/webhook/text"  # fallback text endpoint
    timeout_seconds: 10
    debug: true

audio_feedback:
  enabled: true
  events:
    wake_detected: null           # optional: path to wav file; null => default beep
    recording_stopped: null
    webhook_success: null
    webhook_failure: null

tts:
  rate: 250          # optional speech rate override
  voice_name: "Microsoft Maria Desktop - Portuguese(Brazil)"  # preferred voice by name (case-insensitive)
  voice_index: 1     # fallback legacy index if name not found
  debug: true        # set true to log chosen voice each utterance

webhook_listener:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 5000        # Port for the Flask server
  endpoint: "/response"  # Path for the webhook endpoint
  health_endpoint: "/health"       # Health check path (GET)
  waitress_fallback: true            # Try waitress if Flask dev server fails
  self_test: true                    # Perform loopback health check on startup

# Enable rotating file logging (optional)
logging:
  file_enabled: true
  file_path: "logs/app.log"
  max_bytes: 1048576        # 1 MB before rotation
  backup_count: 5
  encoding: "utf-8"
  level: INFO

# Retry / backoff strategy for webhook deliveries (audio & text)
webhook_retry:
  max_attempts: 3
  base_delay_seconds: 1
  backoff_factor: 2
  max_delay_seconds: 15
  jitter: true

# Shortcut configuration (console + optional global hotkeys)
shortcuts:
  use_global: false           # set true to register system-wide hotkeys (requires 'keyboard')
  start_recording: "ctrl+s"   # manual recording start (when idle)
  abort_recording: "ctrl+a"   # abort active recording (discard)
  finalize_recording: "ctrl+f" # stop & upload current recording
  send_text: "q"              # enter compose (send+tts) mode in console
  tts_only: "v"               # enter compose (tts only) mode in console
  retry_failed: "r"           # retry failed uploads
  exit: "x"                   # request exit (Ctrl+C to fully stop)
  reset_io: "m"               # reset mic + re-init TTS
